[tool.poetry]
name = "chatbot"
version = "0.1.0"
description = ""
authors = ["Rafael Sobucki"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
openai = "^1.37.1"
python-dotenv = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
